### ISSUE TITLE
money send with from an account on UAT environment

### ISSUE THREAD

**Issue by altfatterz** [Dwolla/dwolla-java#9]
Hi,

I have created an account in the UAT environment. I have also created test users sandbox.uat.dwolla.com site. With the java api I can retrieve successfully the account information and also the test user information.
Now I am wondering how can I test the money movement functionality. How can I add funding to my account in order to test the "syncService.send.." functionality. I don't have US bank account, I am based in Europe. 

Thank you.

Zoltan

**Comment by DEATHMETALGORE** [comment]
Aha! Thank you. I didn't know I was able to use Sandbox accounts to log in to the UAT URL.
